#!/bin/bash

shopt -s extglob

# get a list of all files and directories, including hidden ones
all_files=$(printf "%s\n" ./*)

# create an empty array to store the final output
output=()

# add the first two entries to the output array
output+=("./")
output+=("../")

# loop through all the files and directories and add them to the output array
for file in $all_files; do
  # add a slash to directories
  if [[ -d "$file" ]]; then
    output+=("${file%/}/")
  else
    output+=("$file")
  fi
done

# sort the output array, with directories first
sorted_output=($(for item in "${output[@]}"; do echo "$item"; done | LC_COLLATE=en_US sort))

# join the sorted array with commas
echo "${sorted_output[*]}" | tr ' ' ','
echo
