#!/bin/bash
for file in ./*.html; do
    if [ -e "../$file" ]; then
        if [ "$file" -nt "../$file" ]; then
            cp "$file" "../$file"
        fi
    else
        cp "$file" "../$file"
    fi
done
